serenity.report.encoding = UTF-8

webdriver.driver=chrome
webdriver.base.url=https://finance-app-ui.vercel.app
serenity.project.name=E2E Finanzas Personales Fabrica Escuela
serenity.take.screenshots=AFTER_EACH_STEP
serenity.step.delay=1000